### ISSUE TITLE
[Enhancement]: 亲测LibreChat客户端也兼容，只需要配置其librechat.yaml 可以更新一下readme吗

### ISSUE THREAD

**Issue by tsaihsing3** [ErlichLiu/DeepClaude#105]
### 提交前确认

- [x] 我已经搜索过现有的 issues，确认没有类似的功能请求
- [x] 我相信这个功能对大多数用户有价值，而不仅仅对我个人有用

### 相关问题

- 现在的readme里没有librechat，但它也是非常流行的客户端。
- 以下配置亲测deepclaude模型可用。可以加入兼容的客户端列表

### 建议的解决方案

和LobeChat配置是差不多的。参见官方教程，增加一个custon endpoint(官方教程 https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/custom_endpoint)

```    
endpoints:
  custom:
    - name: "DeepClaude"
      apiKey: "********"
      baseURL: "http://127.0.0.1:8000/v1"
      models:
        default: ["deepclaude", "deepgeminiflash", "deepgeminipro"]
        fetch: false
      titleConvo: true
      titleModel: "deepclaude"
      modelDisplayLabel: "DeepClaude"
```
